['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpo7r60s4s/solution_0.py", line 65, in <module>\n    print(Solution().sumOfPower(nums = [1,1,1,1], k = 2))\nTypeError: sumOfPower() got an unexpected keyword argument \'nums\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpo7r60s4s/solution_1.py", line 65, in <module>\n    print(Solution().sumOfPower(nums = [10,20,30,40,50], k = 90))\nTypeError: sumOfPower() got an unexpected keyword argument \'nums\'\n']