['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpx9rp5r86/solution_0.py", line 61, in <module>\n    print(Solution().sumOfPowers(nums = [-10,-20,-30,-40,-50], k = 2))\nTypeError: sumOfPowers() got an unexpected keyword argument \'nums\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpx9rp5r86/solution_1.py", line 61, in <module>\n    print(Solution().sumOfPowers(nums = [5,1,4,2,3], k = 3))\nTypeError: sumOfPowers() got an unexpected keyword argument \'nums\'\n']