['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmptnfeu2s6/solution_0.py", line 74, in <module>\n    print(Solution().maximumTotalDamage(power = [10, 20, 30, 40, 50]))\nTypeError: maximumTotalDamage() got an unexpected keyword argument \'power\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmptnfeu2s6/solution_2.py", line 74, in <module>\n    print(Solution().maximumTotalDamage(power = [5, 5, 5, 5, 5]))\nTypeError: maximumTotalDamage() got an unexpected keyword argument \'power\'\n']