['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpz99mw_wg/solution_0.py", line 98, in <module>\n    print(Solution().longestSpecialPath(edges = [[0,1,10],[0,2,15],[1,3,20],[1,4,25],[2,5,30]], nums = [1,2,3,4,5,6]))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpz99mw_wg/solution_0.py", line 43, in longestSpecialPath\n    insertEdges(edges, helperGraph)\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpz99mw_wg/solution_0.py", line 41, in insertEdges\n    insertAll(0)\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpz99mw_wg/solution_0.py", line 38, in insertAll\n    insertEdgePair([currentEdge[0], currentEdge[2]], [currentEdge[1], currentEdge[2]], container)\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpz99mw_wg/solution_0.py", line 30, in insertEdgePair\n    graphContainer[pair2[1]].append(pair1)\nIndexError: list index out of range\n', 'Outputs do not match']