['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpp_dy_xeh/solution_0.py", line 53, in <module>\n    print(Solution().maximumProcessableQueries(nums = [1,2,3,4,5], queries = [1,2,3,4,6]))\nTypeError: maximumProcessableQueries() got an unexpected keyword argument \'nums\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpp_dy_xeh/solution_1.py", line 53, in <module>\n    print(Solution().maximumProcessableQueries(nums = [2,3,2], queries = [2,2,3]))\nTypeError: maximumProcessableQueries() got an unexpected keyword argument \'nums\'\n']