['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp0j3la3f1/solution_0.py", line 46, in <module>\n    print(Solution().numberOfStableArrays(zero = 4, one = 5, limit = 3))\nTypeError: numberOfStableArrays() got an unexpected keyword argument \'zero\'\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmp0j3la3f1/solution_1.py", line 46, in <module>\n    print(Solution().numberOfStableArrays(zero = 3, one = 3, limit = 2))\nTypeError: numberOfStableArrays() got an unexpected keyword argument \'zero\'\n']