['Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpuh6r5zd0/solution_0.py", line 51, in <module>\n    print(Solution().sumOfPower(nums = [1,1,1,1], k = 2))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpuh6r5zd0/solution_0.py", line 47, in sumOfPower\n    aggregate += pow(2, power_exponent, guardian)\nTypeError: pow expected 2 arguments, got 3\n', 'Traceback (most recent call last):\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpuh6r5zd0/solution_1.py", line 51, in <module>\n    print(Solution().sumOfPower(nums = [10,20,30,40,50], k = 90))\n  File "/var/folders/x3/l43tt5dd3y19dmn0cq8rhm7r0000gq/T/tmpuh6r5zd0/solution_1.py", line 47, in sumOfPower\n    aggregate += pow(2, power_exponent, guardian)\nTypeError: pow expected 2 arguments, got 3\n']